<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)build/$(MSBuildProjectName)/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)build/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)/bin/**;$(MSBuildProjectDirectory)/obj/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
