using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace OhMyLib.SourceGen;

[Generator]
public sealed class EnumAttrPropertyGenerator : IIncrementalGenerator
{
    private const string AutoGenerateAttributeMetadataName = "OhMyLib.Attributes.AutoGenerateEnumAttrPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeInfos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AutoGenerateAttributeMetadataName,
                static (_, _) => true,
                static (ctx, _) => GetAttributeClassInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!);

        var compilationAndAttributes = context.CompilationProvider.Combine(attributeInfos.Collect());
        context.RegisterSourceOutput(compilationAndAttributes, static (spc, source) => GenerateSource(spc, source.Left, source.Right));
    }

    private static AttributeClassInfo? GetAttributeClassInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var autoGenAttr = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.ToDisplayString() == AutoGenerateAttributeMetadataName);

        if (autoGenAttr?.AttributeClass is null)
        {
            return null;
        }

        var targetEnumType = autoGenAttr.NamedArguments
            .FirstOrDefault(static arg => arg.Key == "TargetEnumType")
            .Value
            .Value as INamedTypeSymbol;

        if (targetEnumType is null || targetEnumType.TypeKind != TypeKind.Enum)
        {
            return null;
        }

        var properties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property =>
                property.DeclaredAccessibility == Accessibility.Public &&
                !property.IsStatic &&
                property.GetMethod is not null)
            .Select(static property => new PropertyInfo(property.Name, property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .ToImmutableArray();

        if (properties.IsDefaultOrEmpty)
        {
            return null;
        }

        return new AttributeClassInfo(
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            targetEnumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            targetEnumType.Name,
            targetEnumType.ContainingNamespace.IsGlobalNamespace ? null : targetEnumType.ContainingNamespace.ToDisplayString(),
            properties);
    }

    private static void GenerateSource(SourceProductionContext context, Compilation compilation, ImmutableArray<AttributeClassInfo> attributeInfos)
    {
        foreach (var attrInfo in attributeInfos.Distinct())
        {
            var enumSymbol = compilation.GetTypeByMetadataName(TrimGlobalAlias(attrInfo.TargetEnumFullName));
            if (enumSymbol is null)
            {
                continue;
            }

            var attributeSymbol = compilation.GetTypeByMetadataName(TrimGlobalAlias(attrInfo.AttributeFullName));
            if (attributeSymbol is null)
            {
                continue;
            }

            var enumMembers = new List<EnumMemberInfo>();
            foreach (var member in enumSymbol.GetMembers().OfType<IFieldSymbol>())
            {
                if (!member.HasConstantValue)
                {
                    continue;
                }

                var fieldAttr = member.GetAttributes().FirstOrDefault(attr =>
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attributeSymbol));

                if (fieldAttr?.AttributeClass is null)
                {
                    continue;
                }

                var propertyValues = new Dictionary<string, TypedConstant>(StringComparer.Ordinal);
                foreach (var namedArg in fieldAttr.NamedArguments)
                {
                    propertyValues[namedArg.Key] = namedArg.Value;
                }

                enumMembers.Add(new EnumMemberInfo(member.Name, propertyValues));
            }

            if (enumMembers.Count == 0)
            {
                continue;
            }

            var sourceCode = GenerateExtensionCode(attrInfo, enumMembers);
            context.AddSource(GetHintName(attrInfo), SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GenerateExtensionCode(AttributeClassInfo attrInfo, IReadOnlyCollection<EnumMemberInfo> enumMembers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(attrInfo.TargetEnumNamespace))
        {
            sb.Append("namespace ").Append(attrInfo.TargetEnumNamespace).AppendLine(";");
            sb.AppendLine();
        }

        var enumParameterName = ToCamelCase(attrInfo.TargetEnumName);
        sb.Append("public static class ").Append(attrInfo.TargetEnumName).AppendLine("Extensions");
        sb.AppendLine("{");
        sb.Append("    extension(").Append(attrInfo.TargetEnumName).Append(' ').Append(enumParameterName).AppendLine(")");
        sb.AppendLine("    {");

        foreach (var property in attrInfo.Properties)
        {
            sb.Append("        public ").Append(property.TypeName).Append(' ').Append(property.Name).Append(" => ").Append(enumParameterName).AppendLine(" switch");
            sb.AppendLine("        {");

            foreach (var member in enumMembers)
            {
                if (!member.PropertyValues.TryGetValue(property.Name, out var value))
                {
                    continue;
                }

                sb.Append("            ")
                    .Append(attrInfo.TargetEnumName)
                    .Append('.')
                    .Append(member.Name)
                    .Append(" => ")
                    .Append(FormatValue(value, property.TypeName))
                    .AppendLine(",");
            }

            sb.Append("            _ => throw new ArgumentOutOfRangeException(nameof(")
                .Append(enumParameterName)
                .Append("), ")
                .Append(enumParameterName)
                .AppendLine(", null)");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetHintName(AttributeClassInfo attrInfo)
    {
        return TrimGlobalAlias(attrInfo.TargetEnumFullName)
            .Replace('.', '_')
            .Replace('+', '_') + ".EnumAttrExtensions.g.cs";
    }

    private static string TrimGlobalAlias(string symbolName)
    {
        return symbolName.StartsWith("global::", StringComparison.Ordinal)
            ? symbolName.Substring("global::".Length)
            : symbolName;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string FormatValue(TypedConstant constant, string declaredTypeName)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        if (constant.Kind == TypedConstantKind.Enum &&
            constant.Type is INamedTypeSymbol enumType &&
            constant.Value is not null)
        {
            var member = enumType.GetMembers().OfType<IFieldSymbol>()
                .FirstOrDefault(field => field.HasConstantValue && Equals(field.ConstantValue, constant.Value));
            if (member is not null)
            {
                return "global::" + enumType.ToDisplayString() + "." + member.Name;
            }

            return "(global::" + enumType.ToDisplayString() + ")" + Convert.ToString(constant.Value, CultureInfo.InvariantCulture);
        }

        if (constant.Value is string str)
        {
            return QuoteString(str);
        }

        if (constant.Value is char c)
        {
            return QuoteChar(c);
        }

        if (constant.Value is bool b)
        {
            return b ? "true" : "false";
        }

        if (constant.Value is float f)
        {
            return f.ToString("R", CultureInfo.InvariantCulture) + "F";
        }

        if (constant.Value is double d)
        {
            return d.ToString("R", CultureInfo.InvariantCulture) + "D";
        }

        if (constant.Value is decimal m)
        {
            return m.ToString(CultureInfo.InvariantCulture) + "M";
        }

        if (constant.Value is long or ulong or int or uint or short or ushort or byte or sbyte)
        {
            return Convert.ToString(constant.Value, CultureInfo.InvariantCulture) ?? "0";
        }

        return "((" + declaredTypeName + ")" + FormatPrimitive(constant.Value!) + ")";
    }

    private static string QuoteString(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t") + "\"";
    }

    private static string QuoteChar(char value)
    {
        return value switch
        {
            '\'' => "'\\''",
            '\\' => "'\\\\'",
            '\r' => "'\\r'",
            '\n' => "'\\n'",
            '\t' => "'\\t'",
            _ => "'" + value + "'"
        };
    }

    private static string FormatPrimitive(object value)
    {
        return value switch
        {
            string s => QuoteString(s),
            char c => QuoteChar(c),
            bool b => b ? "true" : "false",
            float f => f.ToString("R", CultureInfo.InvariantCulture) + "F",
            double d => d.ToString("R", CultureInfo.InvariantCulture) + "D",
            decimal m => m.ToString(CultureInfo.InvariantCulture) + "M",
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "null"
        };
    }
}

internal sealed class AttributeClassInfo(
    string attributeFullName,
    string targetEnumFullName,
    string targetEnumName,
    string? targetEnumNamespace,
    ImmutableArray<PropertyInfo> properties) : IEquatable<AttributeClassInfo>
{
    public string AttributeFullName { get; } = attributeFullName;
    public string TargetEnumFullName { get; } = targetEnumFullName;
    public string TargetEnumName { get; } = targetEnumName;
    public string? TargetEnumNamespace { get; } = targetEnumNamespace;
    public ImmutableArray<PropertyInfo> Properties { get; } = properties;

    public bool Equals(AttributeClassInfo? other)
    {
        if (other is null)
        {
            return false;
        }

        return AttributeFullName == other.AttributeFullName &&
               TargetEnumFullName == other.TargetEnumFullName;
    }

    public override bool Equals(object? obj)
    {
        return obj is AttributeClassInfo other && Equals(other);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            var hash = 17;
            hash = hash * 23 + AttributeFullName.GetHashCode();
            hash = hash * 23 + TargetEnumFullName.GetHashCode();
            return hash;
        }
    }
}

internal sealed class PropertyInfo(string name, string typeName)
{
    public string Name { get; } = name;
    public string TypeName { get; } = typeName;
}

internal sealed class EnumMemberInfo(string name, Dictionary<string, TypedConstant> propertyValues)
{
    public string Name { get; } = name;
    public Dictionary<string, TypedConstant> PropertyValues { get; } = propertyValues;
}
