// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OhMyBot.Core.Infrastructure.Data;

#nullable disable

namespace OhMyBot.Core.src.Infrastructure.Data.Migrations.Core
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Privilege")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CoreUsers");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.NotificationSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnabledPlatforms")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QqBotInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QqChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramBotInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId", "NotificationType", "TargetId")
                        .IsUnique();

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PlatformUserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("Platform", "Uid")
                        .IsUnique();

                    b.ToTable("PlatformUserProfiles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PluginOwnedRelation", b =>
                {
                    b.Property<string>("SchemaName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("TableName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("CoreUserIdColumn")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SchemaName", "TableName", "CoreUserIdColumn");

                    b.HasIndex("PluginId");

                    b.ToTable("PluginOwnedRelations");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.NotificationSubscription", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("NotificationSubscriptions")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PlatformUserProfile", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("PlatformProfiles")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", b =>
                {
                    b.Navigation("NotificationSubscriptions");

                    b.Navigation("PlatformProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
