// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OhMyLib;

#nullable disable

namespace OhMyLib.Migrations
{
    [DbContext(typeof(OhMyDbContext))]
    [Migration("20260317033855_V4_AddCheckIn")]
    partial class V4_AddCheckIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OhMyLib.Models.Common.BotUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnOrder(1);

                    b.Property<byte>("OwnerType")
                        .HasColumnType("smallint")
                        .HasColumnOrder(2);

                    b.Property<byte>("Privilege")
                        .HasColumnType("smallint")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("OhMyLib.Models.Common.BotUserCheckin", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastCheckinTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxStreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDays")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("user_checkins");
                });

            modelBuilder.Entity("OhMyLib.Models.Kuro.KuroGameConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GameCharacterUid")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<byte>("GameType")
                        .HasColumnType("smallint")
                        .HasColumnOrder(3);

                    b.Property<long>("KuroUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("TaskType")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("KuroUserId");

                    b.ToTable("kuro_game_configs");
                });

            modelBuilder.Entity("OhMyLib.Models.Kuro.KuroUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BbsTask")
                        .HasColumnType("bigint");

                    b.Property<long?>("BbsUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DevCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DistinctId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<byte>("Region")
                        .HasColumnType("smallint")
                        .HasColumnOrder(3);

                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("BbsUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("kuro_users");
                });

            modelBuilder.Entity("OhMyLib.Models.Telegram.TelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("telegram_users");
                });

            modelBuilder.Entity("OhMyLib.Models.Common.BotUserCheckin", b =>
                {
                    b.HasOne("OhMyLib.Models.Common.BotUser", "User")
                        .WithOne("UserCheckin")
                        .HasForeignKey("OhMyLib.Models.Common.BotUserCheckin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OhMyLib.Models.Kuro.KuroGameConfig", b =>
                {
                    b.HasOne("OhMyLib.Models.Kuro.KuroUser", "KuroUser")
                        .WithMany("GameConfigs")
                        .HasForeignKey("KuroUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KuroUser");
                });

            modelBuilder.Entity("OhMyLib.Models.Kuro.KuroUser", b =>
                {
                    b.HasOne("OhMyLib.Models.Common.BotUser", "OwnerBotUser")
                        .WithOne("KuroUser")
                        .HasForeignKey("OhMyLib.Models.Kuro.KuroUser", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerBotUser");
                });

            modelBuilder.Entity("OhMyLib.Models.Common.BotUser", b =>
                {
                    b.Navigation("KuroUser");

                    b.Navigation("UserCheckin");
                });

            modelBuilder.Entity("OhMyLib.Models.Kuro.KuroUser", b =>
                {
                    b.Navigation("GameConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
