// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OhMyBot.Core.Infrastructure.Data;

#nullable disable

namespace OhMyBot.Core.src.Data.Migrations
{
    [DbContext(typeof(OhMyBotV2DbContext))]
    partial class OhMyBotV2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.AiRouterAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("LoginEmail")
                        .IsUnique();

                    b.ToTable("AiRouterAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Privilege")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CoreUsers");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.HappytukAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginAccount")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("LoginAccount")
                        .IsUnique();

                    b.ToTable("HappytukAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.KuroAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("BbsTaskFlags")
                        .HasColumnType("bigint");

                    b.Property<long>("BbsUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DevCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DistinctId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GameSignSelection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BbsUserId")
                        .IsUnique();

                    b.HasIndex("CoreUserId");

                    b.ToTable("KuroAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.KuroGameRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("KuroAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KuroAccountId", "GameId", "ServerId", "RoleId")
                        .IsUnique();

                    b.ToTable("KuroGameRoles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("BbsTaskFlags")
                        .HasColumnType("bigint");

                    b.Property<string>("CookieCiphertext")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GameSignSelection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("StokenCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Stuid")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("Region", "Stuid")
                        .IsUnique();

                    b.ToTable("MihoyoAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoGameRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameBiz")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("GameUid")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("MihoyoAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MihoyoAccountId", "GameBiz", "GameUid")
                        .IsUnique();

                    b.ToTable("MihoyoGameRoles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.NotificationSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnabledPlatforms")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QqBotInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QqChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramBotInstanceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId", "NotificationType", "TargetId")
                        .IsUnique();

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PlatformUserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("Platform", "Uid")
                        .IsUnique();

                    b.ToTable("PlatformUserProfiles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PluginOwnedRelation", b =>
                {
                    b.Property<string>("SchemaName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("TableName")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("CoreUserIdColumn")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SchemaName", "TableName", "CoreUserIdColumn");

                    b.HasIndex("PluginId");

                    b.ToTable("PluginOwnedRelations");

                    b.HasData(
                        new
                        {
                            SchemaName = "public",
                            TableName = "AiRouterAccounts",
                            CoreUserIdColumn = "CoreUserId",
                            PluginId = "com.ohmybot.airouter"
                        },
                        new
                        {
                            SchemaName = "public",
                            TableName = "KuroAccounts",
                            CoreUserIdColumn = "CoreUserId",
                            PluginId = "com.ohmybot.kuro"
                        },
                        new
                        {
                            SchemaName = "public",
                            TableName = "MihoyoAccounts",
                            CoreUserIdColumn = "CoreUserId",
                            PluginId = "com.ohmybot.mihoyo"
                        },
                        new
                        {
                            SchemaName = "public",
                            TableName = "SklandAccounts",
                            CoreUserIdColumn = "CoreUserId",
                            PluginId = "com.ohmybot.skland"
                        },
                        new
                        {
                            SchemaName = "public",
                            TableName = "HappytukAccounts",
                            CoreUserIdColumn = "CoreUserId",
                            PluginId = "com.ohmybot.happytuk"
                        });
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.SklandAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("CoreUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GameSignSelection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HgTokenCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SignTokenCiphertext")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SklandUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoreUserId");

                    b.HasIndex("SklandUserId")
                        .IsUnique();

                    b.ToTable("SklandAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.SklandGameRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("AutoSignEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SklandAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SklandAccountId", "GameId", "Uid", "RoleId")
                        .IsUnique();

                    b.ToTable("SklandGameRoles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.AiRouterAccount", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("AiRouterAccounts")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.HappytukAccount", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("HappytukAccounts")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.KuroAccount", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("KuroAccounts")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.KuroGameRole", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.KuroAccount", "KuroAccount")
                        .WithMany("Roles")
                        .HasForeignKey("KuroAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KuroAccount");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoAccount", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("MihoyoAccounts")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoGameRole", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoAccount", "MihoyoAccount")
                        .WithMany("Roles")
                        .HasForeignKey("MihoyoAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MihoyoAccount");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.NotificationSubscription", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("NotificationSubscriptions")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.PlatformUserProfile", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("PlatformProfiles")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.SklandAccount", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", "CoreUser")
                        .WithMany("SklandAccounts")
                        .HasForeignKey("CoreUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreUser");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.SklandGameRole", b =>
                {
                    b.HasOne("OhMyBot.Core.Infrastructure.Data.Entities.SklandAccount", "SklandAccount")
                        .WithMany("Roles")
                        .HasForeignKey("SklandAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SklandAccount");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.CoreUser", b =>
                {
                    b.Navigation("AiRouterAccounts");

                    b.Navigation("HappytukAccounts");

                    b.Navigation("KuroAccounts");

                    b.Navigation("MihoyoAccounts");

                    b.Navigation("NotificationSubscriptions");

                    b.Navigation("PlatformProfiles");

                    b.Navigation("SklandAccounts");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.KuroAccount", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.MihoyoAccount", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("OhMyBot.Core.Infrastructure.Data.Entities.SklandAccount", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
